services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skippy_youtube_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      ENV: docker
      DB_USER: user
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_PASSWORD: password
      DB_NAME: skippy_youtube_db
volumes:
  db_data:
